/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckFlightStatusFrame.java
 *
 * Created on Nov 19, 2013, 1:38:48 PM
 */

package GUI;

import javaapplication8.FlightStatus;
import javaapplication8.TravelAgency;



/**
 *
 * @author Danial
 */
public class CheckFlightStatusFrame extends javax.swing.JFrame {

    /** Creates new form CheckFlightStatusFrame */
  private  TravelAgency travelAgency;
    public CheckFlightStatusFrame(TravelAgency travelAgency) {
        this.travelAgency=travelAgency;
        initComponents();
    }

    private CheckFlightStatusFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FlightNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CheckFlightStatusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightstatustextArea = new javax.swing.JTextArea();
        gpbackbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Travel Agency");

        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Enter Flight NO");

        CheckFlightStatusButton.setFont(new java.awt.Font("Tahoma", 0, 18));
        CheckFlightStatusButton.setForeground(new java.awt.Color(51, 102, 255));
        CheckFlightStatusButton.setText("Check Flight Status");
        CheckFlightStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFlightStatusButtonActionPerformed(evt);
            }
        });

        FlightstatustextArea.setColumns(20);
        FlightstatustextArea.setRows(5);
        jScrollPane1.setViewportView(FlightstatustextArea);

        gpbackbutton.setFont(new java.awt.Font("Tahoma", 1, 12));
        gpbackbutton.setForeground(new java.awt.Color(0, 153, 153));
        gpbackbutton.setText("GoBack");
        gpbackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpbackbuttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Serach result:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField1.setForeground(new java.awt.Color(0, 102, 255));
        jTextField1.setText("Flight Number     Departure Time        Arrival Time       Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(gpbackbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckFlightStatusButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(FlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CheckFlightStatusButton)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gpbackbutton)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckFlightStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFlightStatusButtonActionPerformed
     
     if(!FlightNo.getText().equals(""))
     {
     int flightnO=Integer.parseInt(FlightNo.getText());
    FlightStatus flightStatus=travelAgency.checkflightStatus(flightnO);
    if(flightStatus!=null)
    {
     FlightstatustextArea.setText("");
     FlightstatustextArea.append(flightStatus.toString());
     FlightNo.setText("");

    }
    else
    {

    FlightstatustextArea.setText("");
     FlightstatustextArea.append("null");
     FlightNo.setText("");
    }
     }


    }//GEN-LAST:event_CheckFlightStatusButtonActionPerformed

    private void gpbackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpbackbuttonActionPerformed
             MainFrame mainfram=new MainFrame(travelAgency);
        mainfram.setVisible(true);
        dispose();

    }//GEN-LAST:event_gpbackbuttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckFlightStatusFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckFlightStatusButton;
    private javax.swing.JTextField FlightNo;
    private javax.swing.JTextArea FlightstatustextArea;
    private javax.swing.JButton gpbackbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
