/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreditCardPaymentFrame.java
 *
 * Created on Nov 25, 2013, 8:07:48 PM
 */
package GUI;

import javaapplication8.TravelAgency;

/**
 *
 * @author Asad
 */
public class CreditCardPaymentFrame extends javax.swing.JFrame {
    
    private TravelAgency travelAgency;
    private int flightNumber;
    private int membershipID;
    
    public CreditCardPaymentFrame(TravelAgency travelAgency, int flightNumber,int membershipID) 
    {
        initComponents();
        this.travelAgency = travelAgency;
        this.flightNumber = flightNumber;
        this.membershipID = membershipID;
        
        
       
        
    }

    /** Creates new form CreditCardPaymentFrame */
    public CreditCardPaymentFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        creditCardNumberField = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Credit Card Number");

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120)
                        .addComponent(creditCardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditCardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(74, 74, 74)
                .addComponent(submitbutton)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        
        boolean a = travelAgency.authenticateCreditCardNumber(creditCardNumberField.getText());
        
        if (a == true)
        {
        int transactionID = travelAgency.updateAccounts(membershipID,flightNumber);
        
        TicketFrame ticketFrame = new TicketFrame(travelAgency, flightNumber,membershipID,transactionID);
        ticketFrame.setVisible(true);
        }
        
        else if (a==false)
        {
            creditCardNumberField.setText("");
        }
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreditCardPaymentFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField creditCardNumberField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
