/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayStaffList.java
 *
 * Created on Dec 1, 2013, 12:47:38 AM
 */

package GUI;

import java.util.ArrayList;
import java.util.List;
import javaapplication8.Staff;
import javaapplication8.TravelAgency;


/**
 *
 * @author Danial
 */
public class DisplayStaffList extends javax.swing.JFrame {

    /** Creates new form DisplayStaffList */
    private TravelAgency travelAgency;
    public DisplayStaffList() {
        initComponents();
    }

    public DisplayStaffList(TravelAgency travelAgency) {
        this.travelAgency = travelAgency;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StafflistTable = new javax.swing.JTable();
        goback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StaffList");

        StafflistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "STAFFID", "NAME", "POST", "CONTACT", "ADDRESS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        StafflistTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                StafflistTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(StafflistTable);

        goback.setFont(new java.awt.Font("Tahoma", 1, 18));
        goback.setForeground(new java.awt.Color(102, 153, 0));
        goback.setText("GoBack");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(goback)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(goback)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StafflistTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_StafflistTableAncestorAdded

         List<Staff> staffListtemp= new ArrayList<Staff>();

        staffListtemp=travelAgency.getStafflist();

            for (int i = 0; i < staffListtemp.size(); i++) {
                      System.out.println(staffListtemp.get(i).getName());
             for(int j=0;j<6;j++)
              {
                  switch(j)
                {
                    case 0:
                      StafflistTable.setValueAt(String.valueOf(i),i,j);
                   break;
                    case 1:
                      StafflistTable.setValueAt(String.valueOf(staffListtemp.get(i).getStaffID()),i,j);
                    break;
                    case 2:
                        StafflistTable.setValueAt(staffListtemp.get(i).getName(),i,j);
                    break;
                    case 3:
                         StafflistTable.setValueAt(staffListtemp.get(i).getPost(),i,j);
                    break;
                    case 4:
                         StafflistTable.setValueAt(staffListtemp.get(i).getContact(),i,j);
                    break;
                    case 5:
                         StafflistTable.setValueAt(staffListtemp.get(i).getAddress(),i,j);
                    break;
                
                }
            }
        }


    }//GEN-LAST:event_StafflistTableAncestorAdded

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
         ManageStaffFrame MSF = new ManageStaffFrame(travelAgency);
        MSF.setVisible(true);
        dispose();
    }//GEN-LAST:event_gobackActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayStaffList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StafflistTable;
    private javax.swing.JButton goback;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
