/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageStaffFrame.java
 *
 * Created on Nov 19, 2013, 6:48:58 PM
 */

package GUI;

import javaapplication8.TravelAgency;



/**
 *
 * @author Danial
 */
public class ManageStaffFrame extends javax.swing.JFrame {
    private TravelAgency TA;
    /** Creates new form ManageStaffFrame */
    public ManageStaffFrame(TravelAgency TA) {
        this.TA=TA;
        initComponents();
    }

    private ManageStaffFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addstaffbutton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        gobackbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManageStaff");

        addstaffbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addstaffbutton.setForeground(new java.awt.Color(51, 102, 255));
        addstaffbutton.setText("Add Staff Memeber");
        addstaffbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstaffbuttonActionPerformed(evt);
            }
        });

        Deletebutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Deletebutton.setForeground(new java.awt.Color(51, 102, 255));
        Deletebutton.setText("Delete Staff Member");
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        SearchButton.setForeground(new java.awt.Color(51, 102, 255));
        SearchButton.setText("Search Staff Member");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 102, 255));
        jButton4.setText("Display Staff list");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        gobackbutton.setFont(new java.awt.Font("Tahoma", 1, 12));
        gobackbutton.setForeground(new java.awt.Color(0, 153, 153));
        gobackbutton.setText("logout");
        gobackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(gobackbutton)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Deletebutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(addstaffbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(addstaffbutton)
                .addGap(31, 31, 31)
                .addComponent(Deletebutton)
                .addGap(41, 41, 41)
                .addComponent(SearchButton)
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gobackbutton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addstaffbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstaffbuttonActionPerformed
          AddFrame addframe=new AddFrame(TA);
          addframe.setVisible(true);
          dispose();
    }//GEN-LAST:event_addstaffbuttonActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
         DeleteStaffMemberframe deleteFram=new DeleteStaffMemberframe(TA);
         deleteFram.setVisible(true);
         dispose();
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
             SearchStaffFrame searchFrame=new SearchStaffFrame(TA);
             searchFrame.setVisible(true);
             dispose();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void gobackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackbuttonActionPerformed
        AuthenticationFrame authfram=new AuthenticationFrame(TA);
        authfram.setVisible(true);
            dispose();
    }//GEN-LAST:event_gobackbuttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DisplayStaffList dsf=new DisplayStaffList(TA);
        dsf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStaffFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebutton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton addstaffbutton;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
