/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReceiptForm.java
 *
 * Created on Nov 29, 2013, 8:02:13 PM
 */
package GUI;

import javaapplication8.TravelAgency;

/**
 *
 * @author Asad
 */
public class ReceiptForm extends javax.swing.JFrame {

    private TravelAgency travelAgency;
    private int flightNumber;
    private int membershipID;
    private int transactionID;
    
    public ReceiptForm() {
        initComponents();
    }
    
    public ReceiptForm(TravelAgency travelAgency , int flightNumber, int transactionID, int membershipID) 
    {
        
        initComponents();
        this.travelAgency = travelAgency;
        this.flightNumber = flightNumber;
        this.membershipID = membershipID;
        this.transactionID = transactionID;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        generateReceiptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("````````````````````````````TICKET``````````````````````````````````\n`````````````````````SOFTEC TRAVEL AGENCY```````````````````````````");
        jScrollPane1.setViewportView(jTextArea1);

        generateReceiptButton.setText("Generate Receipt");
        generateReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReceiptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(generateReceiptButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(generateReceiptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReceiptButtonActionPerformed
        
        int bookingID = travelAgency.getBookingInfo(membershipID, flightNumber, transactionID);
        travelAgency.getInfoForReceipt(bookingID, transactionID,flightNumber);
        String display = travelAgency.getTicketInfoForReceipt(flightNumber);
        String display2 = travelAgency.getTransactionInfo(transactionID);
        
        jTextArea1.append("\n");
        
        jTextArea1.append(display);
        jTextArea1.append("\n");
        
        jTextArea1.append(display2);
        
        
    }//GEN-LAST:event_generateReceiptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReceiptForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReceiptButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
