/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchFlightFrame.java
 *
 * Created on Nov 19, 2013, 5:45:39 PM
 */
package GUI;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javaapplication8.FlightDescription;
import javaapplication8.TravelAgency;


//import main2.TravelAgency;

/**
 *
 * @author Asad
 */
public class SearchFlightFrame extends javax.swing.JFrame {
 private TravelAgency travelAgency;
    /** Creates new form SearchFlightFrame */
    public SearchFlightFrame() {
        initComponents();
    }
    public SearchFlightFrame(TravelAgency travelAgency)
    {
        
        initComponents();
        this.travelAgency = travelAgency;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gobackbutton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showTextArea = new javax.swing.JTextArea();
        destinationCombobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        airlineCombobox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gobackbutton.setText("Goback");
        gobackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbuttonActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 255));
        jTextField1.setText("FlightNo  DepartureDate  DepartureTime    ArrivalTime      NoOFStopovers                    Seats                      Fare");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Result:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        showTextArea.setColumns(20);
        showTextArea.setRows(5);
        jScrollPane2.setViewportView(showTextArea);

        destinationCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Karachi", "London", "Lahore", "Delhi", "NewYork" }));
        destinationCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationComboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Destination");

        jLabel5.setText("AirLine Company");

        airlineCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PIA", "Airblue", "Shaheen", "Fast", "Any" }));
        airlineCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineComboboxActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Date Of Departure");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gobackbutton)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(561, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(searchButton)
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destinationCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(airlineCombobox, 0, 121, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel4))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(gobackbutton))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(destinationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(airlineCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(69, 69, 69)
                    .addComponent(jLabel4)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackbuttonActionPerformed
       MainFrame mainfram=new MainFrame(travelAgency);
        mainfram.setVisible(true);
        dispose();

    }//GEN-LAST:event_gobackbuttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showTextArea.setText("");
        Date dateFromDateChooser = jDateChooser2.getDate();
        String dateString = String.format("%1$td-%1$tm-%1$tY", dateFromDateChooser);
        
        //String date = dateField.getText();
        String destination = (String) destinationCombobox.getSelectedItem();
        String airline = (String) airlineCombobox.getSelectedItem();
        
        //System.out.println(date);
        //System.out.println(destination);
        //System.out.println(airline);
        List <FlightDescription> showList = new ArrayList<FlightDescription>();
        showList = travelAgency.searchFlightDescription(dateString, destination, airline);
        showTextArea.setText("");
        
        for (int i = 0 ; i <showList.size(); i++) {
            showTextArea.append(String.valueOf(showList.get(i).getFlightNumber()));
            showTextArea.append("                     ");
            showTextArea.append(showList.get(i).getDepartureDate());
            showTextArea.append("                     ");
            showTextArea.append(showList.get(i).getDepartureTime());
            showTextArea.append("                     ");
            showTextArea.append(showList.get(i).getArrivalTime());
            showTextArea.append("                     ");
            showTextArea.append(String.valueOf(showList.get(i).getNoOfStopovers()));
            showTextArea.append("                     ");
            showTextArea.append(String.valueOf(showList.get(i).getSeats()));
            showTextArea.append("                     ");
            showTextArea.append(String.valueOf(showList.get(i).getFare()));
            
            
            
            showTextArea.append("\n");
            
            //flightCombobox.addItem(showList.get(i).getFlightNumber());
        }
        //showTextArea.setText("");
    }//GEN-LAST:event_searchButtonActionPerformed

    private void destinationComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationComboboxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_destinationComboboxActionPerformed

    private void airlineComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineComboboxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_airlineComboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchFlightFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox airlineCombobox;
    private javax.swing.JComboBox destinationCombobox;
    private javax.swing.JButton gobackbutton;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextArea showTextArea;
    // End of variables declaration//GEN-END:variables
}
