/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TicketFrame.java
 *
 * Created on Nov 25, 2013, 7:57:48 PM
 */
package GUI;

import javaapplication8.FlightDescription;
import javaapplication8.TravelAgency;

/**
 *
 * @author Asad
 */
public class TicketFrame extends javax.swing.JFrame {
    
    private TravelAgency travelAgency;
    private int flightNumber;
    private int membershipID;
    private int transactionID;
    //private FlightDescription
    
    public TicketFrame(TravelAgency travelAgency, int flightNumber,int membeshipID,int transactionID) 
    {
        initComponents();
        this.travelAgency = travelAgency;
        this.flightNumber = flightNumber;
        this.membershipID = membeshipID;
        this.transactionID = transactionID;
        
        
        
       
        
    }

    /** Creates new form TicketFrame */
    public TicketFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ticketbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        receiptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("````````````````````````````TICKET``````````````````````````````````\n`````````````````````SOFTEC TRAVEL AGENCY```````````````````````````");
        jScrollPane1.setViewportView(jTextArea1);

        ticketbutton.setText("Generate Ticket");
        ticketbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketbuttonActionPerformed(evt);
            }
        });

        jButton1.setText("Print");

        receiptButton.setText("Show Receipt");
        receiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(ticketbutton)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(receiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ticketbutton)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(receiptButton))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticketbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketbuttonActionPerformed
        String display = travelAgency.getTicketInfo(flightNumber);
        jTextArea1.append("\n");
        jTextArea1.append(display);

        jTextArea1.append("\n");
        //jTextArea1.append("Transaction ID - "+transactionID);
        
        
      
    }//GEN-LAST:event_ticketbuttonActionPerformed

    private void receiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptButtonActionPerformed
        ReceiptForm receiptForm = new ReceiptForm(travelAgency, flightNumber, transactionID, membershipID);
        receiptForm.setVisible(true);
        
        
    }//GEN-LAST:event_receiptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TicketFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton receiptButton;
    private javax.swing.JButton ticketbutton;
    // End of variables declaration//GEN-END:variables
}
